services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge