services:
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:3001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - action: sync+restart
          path: ../src
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ../src/package.json
