services:
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - FRONTEND_PORT
      - VITE_INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - VITE_API_PORT=${API_PORT}
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:$FRONTEND_PORT/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - action: sync+restart
          path: ../
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ../package.json
