services:
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: ../common/docker/Dockerfile
    command: npm run dev
    restart: always
    environment:
      - FRONTEND_PORT
      - VITE_INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - VITE_API_PORT=${API_PORT}
      - VITE_ENABLE_DEV_PAGES=${VITE_ENABLE_DEV_PAGES} #this is for dev testing of backend
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:$FRONTEND_PORT/"]
      interval: 1m30s
      retries: 5
      start_period: 10s
      start_interval: 1s
    develop:
      watch:
        - action: sync+restart
          path: ../
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ../package.json
