name: trascendence

include:
  - backend/elk-stack/docker/docker-compose.elk-stack.yml

x-internal-ports: &internal-ports
  environment:
    - API_PORT
    - USERS_PORT
    - TOURNAMENTS_PORT
    - FRONTEND_PORT
    - PROXY_PORT
    - APP_PORT
    - BLOCKCHAIN_PORT

x-shared-config: &shared-config
  profiles:
    - all
    - app
  volumes:
      - ./common/certs/:/app/certs/:ro
  env_file:
    - .env

services:
  proxy:
    <<: [*shared-config, *internal-ports]
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
    ports:
      - $APP_PORT:$PROXY_PORT
    extends:
      file: backend/proxy/docker/docker-compose.proxy.yml
      service: proxy

  frontend:
    <<: [*shared-config, *internal-ports]
    extends:
      file: frontend/docker/docker-compose.frontend.yml
      service: frontend

  api:
    <<: [*shared-config, *internal-ports]
    depends_on:
      
      users:
        condition: service_healthy
      tournaments:
        condition: service_healthy
      blockchain:
        condition: service_healthy
    extends:
      file: backend/api/docker/docker-compose.api.yml
      service: api

  users:
    <<: [*shared-config, *internal-ports]
    volumes:
      - ./common/certs/:/app/certs/:ro
      - users_db:/app/db/
    extends:
      file: backend/users/docker/docker-compose.users.yml
      service: users

  tournaments:
    <<: [*shared-config, *internal-ports]
    volumes:
      - ./common/certs/:/app/certs/:ro
      - tournaments_db:/app/db
    extends:
      file: backend/tournaments/docker/docker-compose.tournaments.yml
      service: tournaments

  blockchain:
    <<: [*shared-config, *internal-ports]
    extends:
      file: backend/blockchain/docker/docker-compose.blockchain.yml
      service: blockchain

volumes:
  users_db: null
  tournaments_db: null
