name: trascendence

x-internal-ports: &internal-ports
  environment:
    - API_PORT
    - USERS_PORT
    - TOURNAMENTS_PORT
    - FRONTEND_PORT
    - PROXY_PORT
    - APP_PORT

services:
  proxy:
    <<: *internal-ports
    depends_on:
      - frontend
      - api
    ports:
      - '127.0.0.1:$APP_PORT:$PROXY_PORT'
    env_file:
      - .env
    extends:
      file: backend/proxy/docker/docker-compose.proxy.yml
      service: proxy

  frontend:
    <<: *internal-ports
    extends:
      file: frontend/docker/docker-compose.frontend.yml
      service: frontend

  api:
    <<: *internal-ports
    depends_on:
      - users
      - tournaments
    env_file:
      - .env
    extends:
      file: backend/api/docker/docker-compose.api.yml
      service: api

  users:
    <<: *internal-ports
    volumes:
      - users_db:/app/db
    env_file:
      - .env
    extends:
      file: backend/users/docker/docker-compose.users.yml
      service: users

  tournaments:
    <<: *internal-ports
    volumes:
      - tournaments_db:/app/db
    env_file:
      - .env
    extends:
      file: backend/tournaments/docker/docker-compose.tournaments.yml
      service: tournaments

volumes:
  users_db: null
  tournaments_db: null
