services:
  tournaments:
    container_name: tournaments
    build:
      context: ../src
      dockerfile: ../../../common/docker/Dockerfile
    restart: always
    environment:
      - TOURNAMENTS_PORT
      - TOURN_DB_PATH=app/db/tournaments.db
      - REPORT_GUEST_AS_ZERO=${REPORT_GUEST_AS_ZERO:-true} #if we want to change guest reporting approach, this can be set to false
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:$TOURNAMENTS_PORT/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    develop:
      watch:
        - action: sync+restart
          path: ../src
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ../src/package.json