version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:443"
    volumes:
      - ./certs:/certs:ro
    environment:
      - NODE_ENV=development
      - AUTH_URL=http://auth:${AUTH_PORT}
    depends_on:
      - auth

  auth:
    build: ./auth
    expose:
      - "${AUTH_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${AUTH_PORT}
    volumes:
      - auth_data:/var/lib/app

volumes:
  auth_data:
